export const adminTypes = {
    GET_USERS: 'GET_USERS',
    GET_ROLES: 'GET_ROLES',
    GET_USER_ROL_BY_UID: 'GET_USER_ROL_BY_UID',
    GET_USERS_COUNT: 'GET_USERS_COUNT',
    UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',
    USER_ACTIVE: 'USER_ACTIVE',
}

