name: Deploy to EC2

on:
  push:
    branches:
      - master  # Cambia "main" al nombre de tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to EC2
        run: |
          scp -r -i ./ssh/SyncPro.pem ./build/* ec2-user@18.191.244.79:/var/www/html/
